logto-sample/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  get "/", to: "sample#index"
  get "/sign-in", to: "sample#sign_in"
  get "/sign-out", to: "sample#sign_out"
  get "/callback", to: "sample#callback"
end

logto-sample/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

logto-sample/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

logto-sample/app/controllers/articles_controller.rb
require "../logto/client/index"

class ArticlesController < ApplicationController
  before_action :initialize_logto_client

  def index
  end

  def sign_in
    @client.sign_in(redirect_uri: ENV["LOGTO_REDIRECT_URI"])
  end

  def callback
    @client.handle_sign_in_callback(url: request.original_url)
  end

  private

  def initialize_logto_client
    @client = LogtoClient.new(
      config: LogtoClient::Config.new(
        endpoint: ENV["LOGTO_ENDPOINT"],
        app_id: ENV["LOGTO_APP_ID"],
        app_secret: ENV["LOGTO_APP_SECRET"]
      ),
      navigate: ->(uri) { redirect_to(uri, allow_other_host: true) },
      storage: LogtoClient::SessionStorage.new(session)
    )
  end
end

logto-sample/app/controllers/sample_controller.rb
require "logto/client"

class SampleController < ApplicationController
  before_action :initialize_logto_client

  def index
    @is_authenticated = @client.is_authenticated?
    @id_token = @client.id_token
  end

  def sign_in
    @client.sign_in(redirect_uri: request.base_url + "/callback", post_redirect_uri: "/")
  end

  def sign_out
    @client.sign_out(post_logout_redirect_uri: request.base_url)
  end

  def callback
    @client.handle_sign_in_callback(url: request.original_url)
  end

  private

  def initialize_logto_client
    @client = LogtoClient.new(
      config: LogtoClient::Config.new(
        endpoint: ENV["LOGTO_ENDPOINT"],
        app_id: ENV["LOGTO_APP_ID"],
        app_secret: ENV["LOGTO_APP_SECRET"]
        # Uncomment the following lines to specify the scopes and resources that your application needs to access.
        # resources: ["https://shopping.api/"],
        # scopes: ["read:resource"]
      ),
      navigate: ->(uri) { redirect_to(uri, allow_other_host: true) },
      storage: LogtoClient::SessionStorage.new(session)
    )
  end
end

logto-sample/app/helpers/application_helper.rb
module ApplicationHelper
end

logto-sample/app/helpers/articles_helper.rb
module ArticlesHelper
end

logto-sample/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LogtoSample</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

logto-sample/app/views/sample/index.html.erb
<h1>Hello, Rails!</h1>

<p>Is authenticated: <%= @client.is_authenticated? %></p>

<% if @client.is_authenticated? %>
  <a href="<%= sign_out_path %>">Sign out</a>
  <p>Welcome, <%= @client.id_token_claims["username"] %></p>
  <p>Userinfo: <%= @client.fetch_user_info %></p>
  <!-- Uncomment the following line to fetch the access token claims for a resource -->
  <!-- <p>Resource access token: <%# @client.access_token_claims(resource: "https://shopping.api/") %></p> -->
<% else %>
  <a href="<%= sign_in_path %>">Sign in</a>
<% end %>